export const SELECT_TRACK = 'Select a track';
export const TRACK_LIST = [
    'Abu Dhabi',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahrain',
    'Belgium',
    'Brazil',
    'Canada',
    'China',
    'Europe',
    'France',
    'Germany',
    'Great Britain',
    'Hungary',
    'Italy',
    'Japan',
    'Malaysia',
    'Mexico',
    'Monaco',
    'Russia',
    'Singapore',
    'Spain',
    'Turkey',
    'USA'
];
